apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  VAPID_PUBLIC_KEY: {{ .Values.backend.vapid.publicKey | b64enc | quote }}
  VAPID_PRIVATE_KEY: {{ .Values.backend.vapid.privateKey | b64enc | quote }}
  VAPID_SUBJECT: {{ .Values.backend.vapid.subject | b64enc | quote }}
