name = "gomi-no-hi-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

# ローカル開発用（本番は Terraform で管理）
[[kv_namespaces]]
binding = "KV"
id = "d386326dba504d5bb29065133bcb8ec0"

[triggers]
crons = ["0 * * * *"]

[vars]
VAPID_PUBLIC_KEY = "BFzJDbeumq_1cfJDNPnt7g0IVbcMJ08BtadMdhgmpevmlcf9Zfvp-5WoThTm_d7agJAchtiEQ27b_crX7HDwGvg"
VAPID_SUBJECT = "mailto:ti2236sh@gmail.com"
# VAPID_PRIVATE_KEY は wrangler secret put VAPID_PRIVATE_KEY で設定
